[package]
name = "xdp_iphash_to_cpu_cmdline"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
lqos_bus = { path = "../lqos_bus" }
lqos_utils = { path = "../lqos_utils" }
