[package]
name = "lqtop"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.22", features = [ "rt", "macros", "net", "io-util" ] }
lqos_bus = { path = "../lqos_bus" }
anyhow = "1"
tui = "0.19"
crossterm = { version = "0.19", features = [ "serde" ] }
