[package]
name = "lqusers"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
clap = { version = "4", features = ["derive"] }
lqos_config = { path = "../lqos_config" }
anyhow = { workspace = true }
