[package]
name = "lqos_setup"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
colored = "2"
default-net = "0" # For obtaining an easy-to-use NIC list
uuid = { version = "1", features = ["v4", "fast-rng" ] }
lqos_config = { path = "../lqos_config" }
toml = "0.8.8"
