[package]
name = "lqos_bus"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[features]
default = ["equinix_tests"]
equinix_tests = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1"
thiserror = "1"
lqos_config = { path = "../lqos_config" }
lqos_utils = { path = "../lqos_utils" }
lts_client = { path = "../long_term_stats/lts_client" }
tokio = { version = "1", features = [ "rt", "macros", "net", "io-util", "time" ] }
log = "0"
nix = "0"
serde_cbor = "0" # For RFC8949/7409 format C binary objects

[dev-dependencies]
criterion = { version = "0", features = [ "html_reports", "async_tokio"] }

[[bench]]
name = "socket"
harness = false
