[package]
name = "lqos_sys"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
nix = "0"
libbpf-sys = "1"
anyhow = "1"
byteorder = "1.4"
lqos_bus = { path = "../lqos_bus" }
lqos_config = { path = "../lqos_config" }
log = "0"
lqos_utils = { path = "../lqos_utils" }
once_cell = "1"
dashmap = "5"
thiserror = "1"
zerocopy = { version = "0.6.1", features = ["simd"] }

[build-dependencies]
bindgen = "0"
