[package]
name = "lts2_sys"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
log.workspace = true
lqos_config = { path = "../lqos_config" }
serde = { workspace = true, features = ["derive"] }
